# Generated by Django 3.2.11 on 2022-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sku_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=32)),
                ('image_01', models.ImageField(upload_to='')),
                ('image_02', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_03', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_04', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_05', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_06', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_07', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_08', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
